flowchart TD
  A[Admin] --> A1[CRUD categorias y empresas]
  A --> A2[Revision de ofertas]
  A --> A3[Invitar company_admin]

  B[Company Admin] --> B1[CRUD ofertas propias]
  B --> B2[Gestion empleados]
  B --> B3[Invitar company_employee]

  C[Company Employee] --> C1[Canje de cupones]

  D[Client] --> D1[Registro/Login]
  D --> D2[Compra de cupones]
  D --> D3[Historial de cupones]
